import { Component, OnInit } from '@angular/core';
import { of } from 'rxjs';

const features = `
    'angular', 
    'component', 
    'directive',
    'pipes',
    'services',
    'decorators', 
    'interf_class',
    'typeScript',
    'important-files',
    'Data-binding',
    'Styles_CSS_SCSS',
    'ng-build_ng-serve',
    'modules',   
    'life-cycle-hooks',
    'routing_router',
    'lazy-loading', 
    'Change Detection',
    'AoT-compilation', 
    'tree-shaking_',
    'APF',
    'Ivy_Locality', 
    'View-Engine',
    'Promises_Observables',
    'Observables_Subjects',
    'RxJS_',
    'Higher-Order-Mapping-ftns',
    'Forms',
    'ngrx_CRUD',
    'ViewDOM',
    'ContentDOM',
    'Content-Projection',
    'HTTP_HttpClient',
    '@Input_@Output',
    'Git_distd-VCS',
    'Testing_unit',
    'Security',
    'Authorization/Authentication',
    'Node.js',
    'npm',
    'express',
    'CI_CD_Jenkins',
    'Webpack',
    'Cloud_AWS_Azure',
    'Accessability',
    'Angular Material',
    'Flex Layout',
    'PWA - Service Workers',
    'Angular Elements',
    'Web Workers',
    'Angular Universal',
    'Angular Performance',
    'REST_APIs_Swagger',
    'Micro Frontends',
    'Web 3'
`;

const subTopics = [
    ['JavaScript Framework','mobile-desktop','TypeScript','TS Libraries  '], 
    ['Why Components - ', '- class', '- template','Decorators','- @Component({})', '-= selector', '-- templateUrl', '-- styleUrl', '- LC-hooks','- Change detection','this'],
    ['Why Directives','@Directive({})','- attribute-directives', '- template-directives *ngIf','- Components'],
    ['Why Pipes','- transforms data','-- display', 'template', '- Pure', '- Impure','Custom Pipes', '-- @Pipe({})','-- PipeTransform - transform','built-in pipes'],
    ['Why Services','wrt Components','Reuse','- DI - dep Injection','class +','@Injectable({})', '- declare locn', '- nesting','- Sharing','typical tasks','- Providing a Service', '-- providedIn root','providers'], 
    ['Decorators','- Metadata','- Annotations', '- Class'], 
    ['Interfaces', 'Classes','- constructor', '- properties', '- methods', '- events', '-- this'],
    ['tsc', '- .ts files', '- tsconfig.json', '- JS files', '- ngc'],
    ['- package.json', '- angular.json', '-- dist folder','-- node_modules folder' ],
    ['- String interpolation {{x}}','- property binding[]','- event binding()', '- 2-way data binding'],
    ['Why Style - color-size-position', '- CSS', 
    '-- CSS-Box-Model','-- margins','-- padding','-- borders','content',
     'inline - ext', 'ngStyle','ngClass', 
        '- SCSS - variables etc.','-- variables', '-- functions()', '-- mixins','inheritance', 
       'ViewEncapsulation'],
     ['Angular/CLI','- Building', '- Serving the Browser port'],
    ['Modules','NgModule', 'decorator', '- declares Components', '- imports Modules', '- exports Modules','- Can define Service','min 1 Module','Lazy Loading'],
     ['- ngOnChanges()', '- ngOnInit() most popular','- ngDoCheck()', '- ngAfterContentInit()', 
     '- ngAfterContentChecked()', '- ngAfterViewInit()', '- ngAfterViewChecked()','- ngOnDestroy()'],
    ['ComponentRouter', '- router-outlet', '- routerLink', '- ActivatedRoute', '- ParamMap','- Router Guards','Route Resolver'],
    ['forChild','children', '- Feature Modules','- Shared Modules'],
    ['Why Change Detection?','- ngZone', '- manual CD', '- automatic CD','- onPush', '- without ngZone'],
    ['Why AOT','Compile time build', 'No need for Compiler','3 Phases','- 1:Code Analysis','- 2:Code generation','- 3:Template type checking','Benefits'],
    ['Why TreeShake', 'treeshaking in Ivy', 'treeShaking in VE'],
    ['APF - Ang Package Format', 'npm packages','Tooling support','ES versions','Angular CLI','ng-packagr','esm and fesm','.dts files','ESM',
       'Angular 13 APF','- Node package exports', '- es2020 support', '- Ivy partial compilation'
    ],
    ['Ivy new', 'Locality','Incremental DOM','-- Instructions', 'Libraries', '- ngcc', '- Linker   instead', 'Ang Language Service','Compilaion of changes','Ivy - Advantages'],
    ['- ViewEngine old', '- Renderer2', '3 parts -', ' -1: Template Parsing', ' 2: Tree Shaking',' 3: Compilation' , '- Interpreter', '--metadata.json file','ngFactory.js files','JIT or AOT'],
    ['Promises', '- then()', '- future tasks', '- (resolve, reject)','- asynchronous','- catch',' -- ', 
     'Observables','- streams', '- time', '- next()','- Observer','- subscribe','- async pipe','- hot-cold','- Sync or Async', '-- Marble Diagrams'],
    ['Observables','Subjects', '- behaviorSubject', '- asyncSubject', '- replaySubject'],
    ['Reactive Extensions','- library','-- npm install rxjs', '-- asynchronous','-- Event based ops',
    '-- Observable sequences',
    'imps Observable type','Utility ftns','- Convert async to Observables','- iterating over stream','- map vals to types','- filtering streams','- multiple streams',
    'Pipeable operators','- Combination','- Conditional','- Creation',
    '- Errors','- Multi-cast','- Filters','- Transform'],
    ['- ConcatMap','- MergeMap','- SwitchMap','- ExhaustMap'],
    ['Why forms',
    ' -- ',
    '- Template Forms', '-- Template directives','-- ngForm', '-- complex test setup','-- complex validation', '-- [(ngModel)]',
    ' -- ',
    ' -- Template Validation', 
    ' -- ',
    '- Reactive Forms','-- direct access','-- Synchronous data flow','-- simpler test setup','-- simpler validation', '-- new FormControl("")','FormBuilder',  
    ' -- ',
    '  -- Reactive Validation' 
  ],
    ['State Management','BehaviorSubject','- appn State', 'uni-directional','- Store','- Reducer','- Action','- Selector', '- Effects', '-- Entity', '-- Data', 'ComponentStore'],
    ['Whats View DOM', '- ViewChild', '- ViewChildren'],
    ['Whats Content DOM', '- ContentChild', '- ContentChildren'],
    ['Whats transclusion', 'ng-content','- Single Slot','- Multi-Slot','- Conditional'],
    ['CRUD', 'HttpClient', 'HttpInterceptors', 'Angular-web-api-'],
    ['Parent Child commn','- @Input()', '- @Output EventEmitter'],
    ['Parts','- Working tree', '- Stage area','- Local Repository','- Remote Repository','Branches','Fork','stash',
    'Commands - ','- Add','- fetch','- commit','- init','- push','- pull','- log','- status',''], 
    ['Why Test', '- Unit', '-- spec.ts', '--- describe', '--- beforeEach()', '--- it - fit - xit', '--- afterEach', '---- TestBed', '-- Jasmine', '-- Karma', '-- Mocking', '--- Wallaby', 
    '- Integration','-- Shallow','-- Deep', '- End to End', '-- Protractor', '-- Cypress'],
    ['Security','- XSS','-- auto-escaping{{}}',
    '-- CSRF - XSRF', '--- CSRF token','--- HttpClientXsrfModule', 
    '- Output Encoding', 
    '- Sanitization', '-- DomSanitizer','-- bypassSecurityTrustHTML', 
    '- Immutable Code', '- JWTs', '- OWASP', '- SNYK'],
    ['Auhtorization', 'Authentication', '- Auth0', '- OAuth2'],
    ['Node.js'],
    ['npm'],
    ['express','express impn','-- get()','-- listen()'],
    ['Why CI/CD', '- CI - Continuous Integration','- CD - Continuous Development', '- CD - Continuous Delivery', '-- Jenkins'],
    ['Webpack', 'module bundler','Terser plugin', 'Entry Points -', '-- Entry','-- Output', 'Loaders','Plugins'],
    ['Whats the Cloud?', '- AWS - Amazon Web Services', '- Azure'],
    ['Accessability','- ARIA attrbutes', '- WCAG', '- POUR'],
    ['Ang Material', 'Ang CDK'],
    ['Flex-layout', 'display:flex'],
    ['Why PWA','- Service Workers'],
    ['Why Angular Elements','- Custom Elements','- Web Components', '- Framework Agnostic','polyfills',
      'CustomElementRegistry','- createCustomElement() API','NgElementConstructor i/f()','customElements.define()',  '-- CD ftn', '-- data binding','bootstrap to DOM'
    ,'-- Dynamic Content','NgElements class','WithProperties()'],
    ['Why Web Workers', 'Threading', ''],
    ['Why Angular Universal','- SSR - Server Side Rendering'],
    ['How - Angular Performance - ','largest contentful paint', '',
         'Lazy Loading','Angular Universal','PWA-SW','Ivy', 'AOT Compilation','Tree-Shaking', 'Modern Angular'],
    ['RESTitutional file transfer','- Swagger', '- GraphQL'],
    ['Why Micro-FEs','- WebPack5', '- Module Federation'],
    ['- new WWW -','', '']
];


const subTopicsInfo = [
  ['JavaScript Framework','mobile-desktop','TypeScript','TS Libraries  '], 
    ['Components are the most important part of an Ang App', 
      'defines the properties and methods including constructor and events of a Component ', 
      'name of the External HTML file or inline HTML',
      'Decorators - eg @Component',
      'decorator which defines the selector - template and styles of the Component', 
      '-- tag which can be used to install the Component', 
      '-- HTML part of the Component', 
      '-- styles of the Component', 
      `- ngOnChanges() - ngOnInit() most popular - ngDoCheck()- ngAfterContentInit() 
      - ngAfterContentChecked() - ngAfterViewInit() - ngAfterViewChecked() - ngOnDestroy()`,
      'applied to every Component to detect when the Component properties have changed '],
    ['Why Directives',
      '@Directive({})',
      '- attribute-directives', 
      '- template-directives *ngIf',
      '- Components'],
    ['Why Pipes', 
      'transform data for display',
      '- only applied in template',
      '-- template',
     '- Pure', 
     '- Impure',
    'Custom Pipes', 
    '@Pipe({})','-- custom transformation',
    'Date - UpperCase - LowerCase - Currency - Decimal - Percentage - '],
    ['- implemented as a class with @Injectable decorator','simplifies Components',
    'Reuseability in other Components',
     '- Services are injected into Components via the constructor', '@Injectable({})', '- Module or Component','nesting services','- Sharing',
      'fetching data from a server - logging - validating user input ', 'class with injectable decorator','@Injectable({providedIn: \'root\'})','other values','privders:[MyService]'], 
    ['Decorators',
     '- Metadata',
     '- Annotations', 
     '- Class'
    ], 
    ['Interfaces', 
      'Classes',
      '- constructor', 
      '- properties', 
      '- methods', 
      '- events', 
      '-- this'],
    ['tsc', 
    '- .ts files', 
    '- tsconfig.json', 
    '- JS files', 
    '- ngc'],
    ['- package.json', 
    '- angular.json', 
    '-- dist folder',
    '-- node_modules folder' ],
    ['- String interpolation {{x}}',
    '- property binding[]',
    '- event binding()', 
    '- 2-way data binding'],
    ['Why Style - color-size-position', 
    '- CSS', 
    '-- CSS-Box-Model','-- margins','-- padding','-- borders','-- content',
    'inline - ext', 
    'ngStyle',
    'ngClass', 
    '- SCSS - variables etc.','-- variables', '-- functions()', '-- mixins','inheritance',
    'ViewEncapsulation'],
    ['Angular/CLI','- Building', '- Serving the Browser port'],
    ['Modules', 'NgModule configure the injector and the compiler and help organize related things together', 
    '@NgModule({}) decorator',
    '- declares relavent Components', '- imports Modules','exports Modules', 
    '- Can define Service Providers',
    '- required by every Ang appn',
    '- Lazy Loading - uses Feature Modules and Shared Modules'],
    ['ngOnChanges()', 
    '- ngOnInit() most popular',
    '- ngDoCheck()', '- ngAfterContentInit()', 
     '- ngAfterContentChecked()', '- ngAfterViewInit()', '- ngAfterViewChecked()','- ngOnDestroy()'],  
     ['ComponentRouter', '- router-outlet', '- routerLink', '- ActivatedRoute', '- ParamMap','- Router Guards','-- used to prefetch data before route changed'],
    ['forChild','children', '- Feature Modules','- Shared Modules'],
    ['Why Change Detection?','- ngZone', '- manual CD', '- automatic CD','- onPush', '- without ngZone'],
    ['AoT is better due to - ','Compile time build', 'No need for Compiler', '3 Phases - 1:Code Analysis- 2:Code generation- 3:Template type checking',
    '-1 AOT Collector - analyzes the metadata and reps in best manner - recorded in the metadata.json file',
    '-2 Metadata collected from the Code Analysis phase is interpreted by Compilers Static Reflector + check for metadata errors ',
    '-3 Angular template compiler - uses tsc to validate binding expns in template - fullTemplateTypeCheck: true in tsconfig',
    'Benefits are 1: Executable code loaded - 2: inlines all ext HTML+CSS - 3: finds template errors - 4: Reduces injection attacks - 5: Reduces bundle load of Frmwk'],
    ['Remove dead code from the bundle - unused bits', 
    'Ivy tree-shakes - DI-CP-View - Content queries - Animations Pipes i18n core frmwork services LCHs - easier to ship librarries', 
    'View Engine tree-shakes - Static analysis of code and then compiles whats left'],  
     ['APF - Ang Package Format', 
    'npm packages',
    'Tooling support',
    'ES versions',
    'Angular CLI',
    'ng-packagr',   
    'esm and fesm (flattened)',
    '.d.ts files',
    '-  package.json - "type": "module" - No CommonJS Modules',
    'Angular 13 new improved version - Node package exports - es2020 support Ivy partial compilation',
     '- not rely on Internal APIs - using the Node.js - sub-path pattern feature - displaying multiple outputs at each entry point', 
     '- BigInt - Dynamic Import - Nullish Coascing - Optional Chaining -   Promise.allSettled - string#matchAll - globalThis - Module Namespace exports - import.meta', 
     'for Libraries - publishing tsconfig.json - "angularCompilerOptions": {"compilationMode": "partial"}- no particular runtime version - '
  ],
    ['Ivy is new Compilation and Rendering Pipeline using AoT Compilation', 
    ' - single file compilation - components dont need to know about dependencies',
    'Incremental DOM - every component gets compiled to a series of instructions - create DOM trees - updated mutably inplace - comprising the compiler',
    '-- Instructions', 'Libraries', '- ngcc', '- Linker instead', 'Ang Language Service','only recompiles Components that have changed',
    '- adv Tree Shakeable - Reduced size - faster compilation - enhanced testing + debugging - easier dyn comp loading - mobile exp'],
    ['- ViewEngine old - required to transpile .ts to .js', '- abstract base class - to render template to DOM - can be overridden for Custom Rendering - RendererFactory2', '3 parts -', ' -1: Template Parsing + creating Data Structure', ' 2: passing sructure into Interpreter + Tree Shaking'  ,' 3: Compilation' , '- Interpreter', '--metadata.json file',
    'contains the static repn of code in a Component','JIT or AOT'],
    ['Promises',  '- then()', '- future tasks', '- new Promise(resolve, reject)','- asynchronous','Promise.resolve(\'done\').then((val) => {throw new Error("fail")}).then((val) => console.log(val)).catch((err) => console.error(err));',' -- ',
     'Observables','- next()','- Observer','- subscribe','- async pipe','hot - runs all the time without req subscribe()  - cold - requires subscribe ','-- bubbles which identify parts in the timestream'],
    ['Observables','Subjects', '- behaviorSubject', '- asyncSubject', '- replaySubject'],
    ['Reactive Extensions',
    '- library','-- npm install rxjs', '-- asynchronous','-- Event based ops',
    'imps Observable type','Utility ftns','- Convert async to Observables','- iterating over stream','- map vals to types','- filtering streams','- multiple streams',
    'Pipeable operators','- Combination','- Conditional','- Creation',
    '- Errors','- Multi-cast','- Filters','- Transform'],
    ['- Sequence opn (order of opns is important) - map values to inner Observable subscribe and emit in order - delayed subscribe to inner Observables',
    '- (alias FlatMap) Parallel opn - Multiple simultaneous active inner subscriptions - possible memory leaks - subscribes immed to inner Observables -  map to Observable with inner timer or a stream of DOM events',
    '-- map to Observable - complete previous inner Observable - emit values - immed cancel prev opn and emit new one - can have a cancelling operator - ',
    '- ExhaustMap - projects each source value to an Observale which is merged in the o/p Observable only if prev has completed - maps each value to an Observable then flattens all the inner Observables usng exhaust'],
    ['Why forms - to handle user input - eg Login - Register',
    ' -- ',
    '- Template Forms', '-- Template directives for object Model','-- ngForm', 'more complex test setup','-- complex validation','',
    ' -- ',
    ' --- Template Validation',
    ' -- ',
    '- Reactive Forms','-- direct access to Object Model','-- Synchronous data flow','simpler test setup','-- simpler validation','-- Data','= new FormControl("")',
    ' -- ',
    '--- Reactive Validation'
  ],
    ['State Management - Reactive State for Angular - a group of angular libraries for Reactive extensions - inspired by the Redux pattern - derives state using RxJS - helps simplify appns with many user interactions and multiple data sources',
    'BehaviorSubject',
    'appn State',
    '- enforces a unidirectional sequence of operations ',
    '- ngrx/Store is the main appn State',
    '- Reducer are pure functions which take an action and output data to state or on to Effects (if async)',
    '- Action - acts as input to Reducer to produce new State',
    '- Selector - Read state data - are pure functions for getting slices of the state from the Store - how appns listen to State Changes', 
    '- Effects - (side Effects - commn with ext API HTTP or dispatching another action  ) asynchronous parts of code which take effect after Reducer functions', 
    '-- Entity - data - ',
    '-- Data - Simplifying the case for many CRUD operations',
     '--- if the state is confined to one Component then this can be used',
    'implementation of ngrx ', '- Auth0 SDK'
    ], 
    ['Whats View DOM', '- ViewChild', '- ViewChildren'],
    ['Whats Content DOM', '- ContentChild', '- ContentChildren'],
    ['Whats transclusion', 'ng-content','- Single Slot','- Multi-Slot','- Conditional'],
    ['CRUD', 'HttpClient', 'HttpInterceptors', 'Angular-web-api-'],
    ['Parent Child commn','- @Input()', '- @Output EventEmitter'],
    ['Parts','- Working tree', '- Stage area','- Local Repository','- Remote Repository','Branches','Fork','stash',
    'Commands - ','- Add','- fetch','- commit','- init','- push','- pull','- log','- status',''], 
   
    ['Why Test', '- Unit', '-- spec.ts', '--- describe', '--- beforeEach()', '--- it - fit - xit', '--- afterEach', '---- TestBed', '-- Jasmine', '-- Karma', '-- Mocking', '--- Wallaby', 
    '- Integration','-- Shallow','-- Deep', '- End to End', '-- Protractor', '-- Cypress'],
    ['Security', 
    '- XSS (Cross Site Scripting Vulnerability) - allows attacker to control users appn in browser',
    '-- Angular auto-escaping for {{}} interpolation', 
    '- CSRF = XSRF (Cross Site Request Forgery) exploits users security by sending an unwanted request to server wrt cookies',
    '- CSRF - cookie-to-header token - protected by server side appn generates token to protect against CSRF attacks',
    '--- HttpClientXsrfModule.withOptions({cookieName: \'XSRF-TOKEN\',headerName: \'X-XSRF-TOKEN\'})',
    '- Strings are replaced by their text values', 
    '- is the inspection of untrusted values - turning it into a safe to use in DOM value - Angular auto sanitizes untrusted values for HTML|styles|URLs ',
    '-- DomSanitizer - used to allow code through',
    '-- constructor(private sanitizer : DomSanitizer) {} - getHtmlSnippet() {let safeHtml = `<img src="..." oerror="alert(\'Failed to load image\')">`;return this.sanitizer.bypassSecurityTrustHtml(safeHtml);}', 
    ' - using Observables for data instead of the actual data - means the code cant be accidentally changed', 
    '- JSON Web Tokens - appn talks to server that produces Token - passed as Authorization Header to prove authentication', 
    '- OWASP - a foundation works to improve security of S/W ', 
    '- npm install -g snyk - snyk test - tracks over 23 security vulnerabilities for Angular related Modules'],
    ['Auhtorization', 'Authentication', '- Auth0', '- OAuth2'],
    ['Node.js'],
    ['- Node Package Manager'],
    ['- Most popular Web framework - A backend web appn for Node.js for building Web appns and APIs - provides mechanisms for writing handlers for requests with diff HTTP verbs at diff URL Paths- routes ',
    '-- const express = require(\'express\'); const app = express(); const port = 3000;','-- app.get(\'/\', function(req, res) {res.send(\'Hello World!\')}); - ','--  app.listen(port, function() { console.log(\`Example app listening on port ${port}!\`)}); ' 
  ],
    ['Why CI/CD', 
  '- CI - Continuous Integration',
  '- CD - Continuous Development', 
  '- CD - Continuous Delivery', 
  '-- Jenkins'],
    ['Webpack', 
    'module bundler',
    'Terser plugin', 
    'Entry Points -', 
    '-- Entry',
    '-- Output', 
    'Loaders',
    'Plugins'],
    ['- AWS - Amazon Web Services', '- Azure'],
    ['Accessability','- ARIA attrbutes', '- WCAG', '- POUR'],
   ['Ang Material', 'Ang CDK'],
    ['Flex-layout', 
        'display:flex'],
    ['Progressive Web Applications - ',
      '- Service Workers'
    ],
    ['let us Mix languages together - eg Angular and React','- Custom Elements','- Web Components', '- Framework Agnostic','polyfills',
    'CustomElementRegistry','- createCustomElement() API','NgElementConstructor i/f()','customElements.define()',  '-- CD ftn', '-- data binding','bootstrap to DOM'
    ,'-- Dynamic Content','- NgElement class','-- let us add Type Infon to the NgElement class'],
    ['Web Workers permit multithreading in Angular', 'Threading', 
      ''],
    ['Angular Universal is a UI Framework - Accessability - mobile friendly','- SSR - Server Side Rendering'],
    ['How - Angular Performance - ','- sourceMap Explorer','LCP - largest Component Paint  ',' - Lazy Loading','- Angular Universal','- PWA-SW','- Ivy', '- AOT Compilation','- Tree-Shaking', '- Modern Angular'],
    ['RESTitutional file transfer','- Swagger', '- GraphQL'],
    ['Why Micro-FEs','- WebPack5', '- Module Federation'],  

    ['- new WWW -','', ''] 
];
 

@Component({
  selector: 'app-ts-menu',
  templateUrl: './ts-menu.component.html',
  styleUrls: ['./ts-menu.component.scss']
})
export class TsMenuComponent implements OnInit {
  
  isScreenSmall = false;

  ts_list = of(features.split(','));
  ts_sublist = subTopics; // gives indiv arrays
  
  ts_strArr: string[] = [];
  ts_subStrArr: string[6][] = [];
  
  tsFeatureIndex = 0;
  tsFeatureSubIndex = 0;

  tsInfo: string = ``;

  constructor() { }

  ngOnInit(): void {
      console.log('ngOnInit()');
      let arr = this.ts_sublist;
  }

  getInfo(i: number, j: number){
      this.tsInfo = subTopicsInfo[i][j];       
      this.tsFeatureSubIndex = j;
  }

  removeQuote(str: string): string{
      return str.replace(/'/g,'');
  }

  showTSFeatures(inx: number){
      this.tsFeatureIndex = inx;
  }
}
